In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [2]:
df=pd.read_csv("D:\TA\Random_Forest\dataset\keparahan_1.csv")

df.drop('No Document', axis=1, inplace=True)
df.drop('title', axis=1, inplace=True)
df.drop('Description', axis=1, inplace=True)
df=df.dropna(axis=0)

df['Mati']=df.Mati.astype(int)
df['Sakit']=df.Sakit.astype(int)

df

Mati  Sakit Keparahan
0        0      0    rendah
1        1     19    sedang
2       15    254     parah
3        1      5    rendah
4        0      0    rendah
...    ...    ...       ...
1229     0      1    rendah
1230     0      0    rendah
1231     0     11    sedang
1232     3      1    rendah
1233     0      4    rendah

[1234 rows x 3 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1234 entries, 0 to 1233
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Mati       1234 non-null   int32 
 1   Sakit      1234 non-null   int32 
 2   Keparahan  1234 non-null   object
dtypes: int32(2), object(1)
memory usage: 28.9+ KB


In [4]:
parah = df

key = {'rendah' : 1, 'sedang' : 2, 'parah' : 3}
parah['key'] = [key[r] for r in parah['Keparahan']]

In [5]:
parah.head()

Mati  Sakit Keparahan  key
0     0      0    rendah    1
1     1     19    sedang    2
2    15    254     parah    3
3     1      5    rendah    1
4     0      0    rendah    1

In [6]:
x = parah[['Mati', 'Sakit']]
y = parah['key'] 

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=3)

In [8]:
len (x_train)

987

In [9]:
len (x_test)

247

In [10]:
clf = RandomForestClassifier()
clf.fit(x_train,y_train)

RandomForestClassifier()

In [11]:
y_pred = clf.predict(x_test)
y_pred

array([1, 1, 3, 1, 1, 1, 1, 1, 3, 1, 1, 3, 1, 3, 1, 1, 1, 3, 1, 1, 1, 1,
       1, 1, 3, 1, 3, 3, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 3, 1, 1, 1, 1, 3, 3, 3, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 3, 2, 1, 1, 2, 3, 1, 1,
       2, 3, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 2, 3, 1, 1, 1, 3, 1, 1, 1,
       1, 3, 1, 1, 1, 2, 3, 1, 1, 2, 2, 1, 1, 1, 1, 3, 1, 3, 1, 1, 1, 3,
       1, 3, 1, 1, 1, 1, 3, 3, 3, 1, 2, 3, 3, 1, 3, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 2, 1, 1, 3, 1, 3, 1, 1, 2, 3, 1, 3, 1, 1, 1, 2, 2, 1, 1, 1,
       3, 1, 1, 2, 3, 3, 1, 3, 3, 1, 1, 3, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 3, 1, 2, 3, 3, 1, 1, 1, 3, 2, 1, 2, 3, 1, 1, 1, 1, 1, 1,
       1, 3, 1, 1, 1], dtype=int64)

In [12]:
r2_score(y_test, y_pred)

0.9938166524808492

In [13]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[171   0   0]
 [  0  25   1]
 [  0   0  50]]
Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00       171
           2       1.00      0.96      0.98        26
           3       0.98      1.00      0.99        50

    accuracy                           1.00       247
   macro avg       0.99      0.99      0.99       247
weighted avg       1.00      1.00      1.00       247

Accuracy: 0.9959514170040485
